# Compile Football-Data Seasons Data

In [1]:
import pathlib
import sys
import datetime

import numpy as np
import pandas as pd

# Load the "autoreload" extension
%load_ext autoreload
# always reload modules marked with "%aimport"
%autoreload 1
# add the 'src' directory to path to import modules
src_dir = pathlib.Path().cwd().resolve().parent / 'src'
#src_dir = os.path.join(os.getcwd(), os.pardir, 'src')
sys.path.append(src_dir)
# import my class code from the source
# %aimport src-dir.filename

pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

DATA_DIR = pathlib.Path().cwd().resolve().parent / 'data'
RAW_DATA_DIR = DATA_DIR / '01-raw'
INTERIM_DATA_DIR = DATA_DIR / '02-interim' / 'football-data'

## Select Raw Data Source, League and Seasons

In [2]:
league = 'english-premier-league'
GAME_DATA_DIR = RAW_DATA_DIR / 'football-data' / 'United-Kingdom' / league

# seasons 2009-2010 through to 2017-2018
start_year = 2009 ; end_year = 2018
seasons = [str(year) + '-' + str(year+1) for year in range(start_year, end_year)]
print(GAME_DATA_DIR)
save_file_name = str('football-data-' + league + '.csv')

/media/david/5C14F53A14F517AA/code/ana_py37/projects/soccer-predictions/data/01-raw/football-data/United-Kingdom/english-premier-league

In [3]:
# Compile Seasons into one file
season_dfs=[]
for season in seasons:
    season_fp = GAME_DATA_DIR / season / 'football-data-co-uk' / 'season-data' / str(season + '.csv')
#     season_dfs = pd.read_csv(season_fp)
#     print(season_df.head())
    season_df = pd.read_csv(season_fp, dayfirst=True, parse_dates=['Date'])
    season_df['season'] = season
    season_dfs.append(season_df)

df = pd.concat(season_dfs, axis=0, sort=True)
    
df.head()

   AC  AF  AR  AS  AST  AY    AwayTeam  B365A  B365D  B365H   BSA  BSD   BSH    BWA   BWD   BWH  Bb1X2  BbAH  BbAHh  BbAv<2.5  BbAv>2.5  BbAvA  BbAvAHA  BbAvAHH  BbAvD  BbAvH  BbMx<2.5  BbMx>2.5  BbMxA  BbMxAHA  BbMxAHH  BbMxD  BbMxH  BbOU       Date Div  FTAG  FTHG FTR    GBA   GBD   GBH  HC  HF  HR  HS  HST  HTAG  HTHG HTR  HY     HomeTeam   IWA  IWD  IWH    LBA  LBD   LBH  PSA  PSCA  PSCD  PSCH  PSD  PSH        Referee   SBA   SBD   SBH    SJA   SJD   SJH   VCA  VCD   VCH    WHA  WHD   WHH     season
0   6  14   0  14    7   2       Wigan   5.50   3.60   1.67   5.5  3.5  1.62   5.00  3.40  1.65     37  21.0    0.0      1.81      1.92   5.33     3.99     1.22   3.51   1.66      1.91      2.04   6.05     4.40     1.28   3.77   1.72    32 2009-08-15  E0     2     0   A   5.25  3.50  1.67   4  15   0  11    5     1     0   A   2  Aston Villa   4.9  3.5  1.7   4.50  3.3  1.67  NaN   NaN   NaN   NaN  NaN  NaN  M Clattenburg   5.0  3.40  1.65   5.50  3.60  1.67   5.0  3.4  1.70   5.50  3.4  1.70  2009-2010
1   4   9   0   8    5   1    Man City   2.10   3.25   3.60   2.2  3.2  3.30   2.00  3.15  3.40     38  24.0    0.0      1.71      2.04   2.12     1.54     2.38   3.24   3.37      1.78      2.15   2.25     1.60     2.58   3.35   3.78    33 2009-08-15  E0     2     0   A   2.10  3.25  3.40   5  12   0  17    9     1     0   A   2    Blackburn   2.2  3.2  3.2   2.10  3.2  3.00  NaN   NaN   NaN   NaN  NaN  NaN         M Dean   2.1  3.25  3.15   2.20  3.25  3.30   2.2  3.2  3.25   2.15  3.2  3.50  2009-2010
2   7  10   0  20   13   1  Sunderland   3.25   3.25   2.25   3.3  3.2  2.20   3.15  3.15  2.15     38  23.0    0.0      1.66      2.12   3.15     2.23     1.61   3.20   2.24      1.70      2.25   3.40     2.33     1.68   3.31   2.37    33 2009-08-15  E0     1     0   A   3.10  3.25  2.25   4  16   0  11    3     1     0   A   2       Bolton   3.2  3.2  2.2   3.00  3.2  2.10  NaN   NaN   NaN   NaN  NaN  NaN     A Marriner   2.9  3.20  2.25   3.10  3.25  2.30   3.1  3.2  2.25   3.20  3.2  2.30  2009-2010
3   4  15   0   7    3   2        Hull  21.00   6.50   1.17  19.0  5.5  1.20  13.00  6.00  1.17     38  22.0    0.0      2.26      1.58  16.39    12.96     1.02   6.26   1.17      2.44      1.67  23.14    17.05     1.03   7.71   1.20    34 2009-08-15  E0     1     2   H  15.00  6.00  1.20  12  13   0  26   12     1     1   D   1      Chelsea  14.0  5.5  1.2  12.00  5.5  1.17  NaN   NaN   NaN   NaN  NaN  NaN        A Wiley  15.0  5.75  1.17  17.00  6.50  1.18  17.0  6.0  1.17  21.00  6.5  1.17  2009-2010
4   9  13   0  15    9   0     Arsenal   2.30   3.25   3.20   2.2  3.2  3.25   2.25  3.15  2.95     38  24.0    0.0      1.70      2.06   2.28     1.63     2.20   3.21   3.07      1.77      2.20   2.42     1.73     2.27   3.34   3.34    34 2009-08-15  E0     6     1   A   2.30  3.25  3.00   4  11   0   8    5     3     0   A   0      Everton   2.3  3.1  3.1   2.25  3.0  2.88  NaN   NaN   NaN   NaN  NaN  NaN       M Halsey   2.2  3.20  3.00   2.25  3.25  3.25   2.3  3.3  2.90   2.30  3.2  3.20  2009-2010

In [4]:
seasons_df = df.copy(deep=True)

# Drop unnecesary columns
# Referee is not available for the full data set, and Half Time Result and Full Time Result can be calculated
seasons_df.drop(columns=['Div', 'FTR', 'HTR', 'Referee', ], inplace=True)
seasons_df.rename(columns={'Date': 'date', 'HomeTeam': 'h', 'AwayTeam': 'a',
                          'FTHG': 'h_ftgoals', 'FTAG': 'a_ftgoals', 'HTHG': 'h_htgoals', 'HTAG': 'a_htgoals',
                         'HS': 'h_shots', 'AS': 'a_shots', 'HST': 'h_sot', 'AST': 'a_sot',
                         'HF': 'h_fouls', 'AF': 'a_fouls', 'HC': 'h_corners', 'AC': 'a_corners',
                         'HY': 'h_ycards', 'AY': 'a_ycards', 'HR': 'h_rcards', 'AR': 'a_rcards'}, inplace=True)

columns = {'B365H': 'odds_hwin_bet365', 'B365D': 'odds_draw_bet365', 'B365A': 'odds_awin_bet365',
          'BWH': 'odds_hwin_BW', 'BWD': 'odds_draw_BW', 'BWA': 'odds_awin_BW',
          'GBH': 'odds_hwin_GB', 'GBD': 'odds_draw_GB', 'GBA': 'odds_awin_GB',
          'IWH': 'odds_hwin_IW', 'IWD': 'odds_draw_IW', 'IWA': 'odds_awin_IW',
          'LBH': 'odds_hwin_LB', 'LBD': 'odds_draw_LB', 'LBA': 'odds_awin_LB',
          'SBH': 'odds_hwin_SB', 'SBD': 'odds_draw_SB', 'SBA': 'odds_awin_SB',
          'WHH': 'odds_hwin_WH', 'WHD': 'odds_draw_WH', 'WHA': 'odds_awin_WH',
          'SJH': 'odds_hwin_SJ', 'SJD': 'odds_draw_SJ', 'SJA': 'odds_awin_SJ',
          'VCH': 'odds_hwin_VC', 'VCD': 'odds_draw_VC', 'VCA': 'odds_awin_VC',           
          'BSH': 'odds_hwin_BS', 'BSD': 'odds_draw_BS', 'BSA': 'odds_awin_BS',
          'PSH': 'odds_hwin_pinn', 'PSD': 'odds_draw_pinn', 'PSA': 'odds_awin_pinn',
           'Bb1X2': 'n_Bb1X2',
           'BbMxH': 'odds_hwin_bbmax', 'BbMxD': 'odds_draw_bbmax', 'BbMxA': 'odds_awin_bbmax',
           'BbAvH': 'odds_hwin_bbmean', 'BbAvD': 'odds_draw_bbmean', 'BbAvA': 'odds_awin_bbmean',
           'BbOU': 'n_BbOU',
           'BbMx>2.5': 'odds_ftgoalso2.5_bbmax', 'BbAv>2.5': 'odds_ftgoalso2.5_bbmean',
           'BbMx<2.5': 'odds_ftgoalsu2.5_bbmax', 'BbAv<2.5': 'odds_ftgoalsu2.5_bbmean',
           'BbAH': 'n_BbAsian',
           'BbAHh': 'BbAsian_handicap',
           'BbMxAHH': 'odds_asianhome_bbmax', 'BbAvAHH': 'odds_asianhome_bbmean',
           'BbMxAHH': 'odds_asianhome_bbmax', 'BbAvAHH': 'odds_asianhome_bbmean',
           'BbMxAHA': 'odds_asianaway_bbmax', 'BbAvAHH': 'odds_asianaway_bbmean',
           'BbMxAHA': 'odds_asianaway_bbmax', 'BbAvAHA': 'odds_asianaway_bbmean',
           'PSCH': 'clodds_hwin_pinn', 'PSCD': 'clodds_draw_pinn', 'PSCA': 'clodds_away_pinn'}
seasons_df.rename(columns=columns, inplace=True)


seasons_df.head()

,a_corners,a_fouls,a_rcards,a_shots,a_sot,a_ycards,a,odds_awin_bet365,odds_draw_bet365,odds_hwin_bet365,odds_awin_BS,odds_draw_BS,odds_hwin_BS,odds_awin_BW,odds_draw_BW,odds_hwin_BW,n_Bb1X2,n_BbAsian,BbAsian_handicap,odds_ftgoalsu2.5_bbmean,odds_ftgoalso2.5_bbmean,odds_awin_bbmean,odds_asianaway_bbmean,odds_asianaway_bbmean,odds_draw_bbmean,odds_hwin_bbmean,odds_ftgoalsu2.5_bbmax,odds_ftgoalso2.5_bbmax,odds_awin_bbmax,odds_asianaway_bbmax,odds_asianhome_bbmax,odds_draw_bbmax,odds_hwin_bbmax,n_BbOU,date,a_ftgoals,h_ftgoals,odds_awin_GB,odds_draw_GB,odds_hwin_GB,h_corners,h_fouls,h_rcards,h_shots,h_sot,a_htgoals,h_htgoals,h_ycards,h,odds_awin_IW,odds_draw_IW,odds_hwin_IW,odds_awin_LB,odds_draw_LB,odds_hwin_LB,odds_awin_pinn,clodds_away_pinn,clodds_draw_pinn,clodds_hwin_pinn,odds_draw_pinn,odds_hwin_pinn,odds_awin_SB,odds_draw_SB,odds_hwin_SB,odds_awin_SJ,odds_draw_SJ,odds_hwin_SJ,odds_awin_VC,odds_draw_VC,odds_hwin_VC,odds_awin_WH,odds_draw_WH,odds_hwin_WH,season
0,6,14,0,14,7,2,Wigan,5.50,3.60,1.67,5.5,3.5,1.62,5.00,3.40,1.65,37,21.0,0.0,1.81,1.92,5.33,3.99,1.22,3.51,1.66,1.91,2.04,6.05,4.40,1.28,3.77,1.72,32,2009-08-15,2,0,5.25,3.50,1.67,4,15,0,11,5,1,0,2,Aston Villa,4.9,3.5,1.7,4.50,3.3,1.67,NaN,NaN,NaN,NaN,NaN,NaN,5.0,3.40,1.65,5.50,3.60,1.67,5.0,3.4,1.70,5.50,3.4,1.70,2009-2010
1,4,9,0,8,5,1,Man City,2.10,3.25,3.60,2.2,3.2,3.30,2.00,3.15,3.40,38,24.0,0.0,1.71,2.04,2.12,1.54,2.38,3.24,3.37,1.78,2.15,2.25,1.60,2.58,3.35,3.78,33,2009-08-15,2,0,2.10,3.25,3.40,5,12,0,17,9,1,0,2,Blackburn,2.2,3.2,3.2,2.10,3.2,3.00,NaN,NaN,NaN,NaN,NaN,NaN,2.1,3.25,3.15,2.20,3.25,3.30,2.2,3.2,3.25,2.15,3.2,3.50,2009-2010
2,7,10,0,20,13,1,Sunderland,3.25,3.25,2.25,3.3,3.2,2.20,3.15,3.15,2.15,38,23.0,0.0,1.66,2.12,3.15,2.23,1.61,3.20,2.24,1.70,2.25,3.40,2.33,1.68,3.31,2.37,33,2009-08-15,1,0,3.10,3.25,2.25,4,16,0,11,3,1,0,2,Bolton,3.2,3.2,2.2,3.00,3.2,2.10,NaN,NaN,NaN,NaN,NaN,NaN,2.9,3.20,2.25,3.10,3.25,2.30,3.1,3.2,2.25,3.20,3.2,2.30,2009-2010
3,4,15,0,7,3,2,Hull,21.00,6.50,1.17,19.0,5.5,1.20,13.00,6.00,1.17,38,22.0,0.0,2.26,1.58,16.39,12.96,1.02,6.26,1.17,2.44,1.67,23.14,17.05,1.03,7.71,1.20,34,2009-08-15,1,2,15.00,6.00,1.20,12,13,0,26,12,1,1,1,Chelsea,14.0,5.5,1.2,12.00,5.5,1.17,NaN,NaN,NaN,NaN,NaN,NaN,15.0,5.75,1.17,17.00,6.50,1.18,17.0,6.0,1.17,21.00,6.5,1.17,2009-2010
4,9,13,0,15,9,0,Arsenal,2.30,3.25,3.20,2.2,3.2,3.25,2.25,3.15,2.95,38,24.0,0.0,1.70,2.06,2.28,1.63,2.20,3.21,3.07,1.77,2.20,2.42,1.73,2.27,3.34,3.34,34,2009-08-15,6,1,2.30,3.25,3.00,4,11,0,8,5,3,0,0,Everton,2.3,3.1,3.1,2.25,3.0,2.88,NaN,NaN,NaN,NaN,NaN,NaN,2.2,3.20,3.00,2.25,3.25,3.25,2.3,3.3,2.90,2.30,3.2,3.20,2009-2010

In [5]:
seasons_df.describe()

,a_corners,a_fouls,a_rcards,a_shots,a_sot,a_ycards,odds_awin_bet365,odds_draw_bet365,odds_hwin_bet365,odds_awin_BS,odds_draw_BS,odds_hwin_BS,odds_awin_BW,odds_draw_BW,odds_hwin_BW,n_Bb1X2,n_BbAsian,BbAsian_handicap,odds_ftgoalsu2.5_bbmean,odds_ftgoalso2.5_bbmean,odds_awin_bbmean,odds_asianaway_bbmean,odds_asianaway_bbmean,odds_draw_bbmean,odds_hwin_bbmean,odds_ftgoalsu2.5_bbmax,odds_ftgoalso2.5_bbmax,odds_awin_bbmax,odds_asianaway_bbmax,odds_asianhome_bbmax,odds_draw_bbmax,odds_hwin_bbmax,n_BbOU,a_ftgoals,h_ftgoals,odds_awin_GB,odds_draw_GB,odds_hwin_GB,h_corners,h_fouls,h_rcards,h_shots,h_sot,a_htgoals,h_htgoals,h_ycards,odds_awin_IW,odds_draw_IW,odds_hwin_IW,odds_awin_LB,odds_draw_LB,odds_hwin_LB,odds_awin_pinn,clodds_away_pinn,clodds_draw_pinn,clodds_hwin_pinn,odds_draw_pinn,odds_hwin_pinn,odds_awin_SB,odds_draw_SB,odds_hwin_SB,odds_awin_SJ,odds_draw_SJ,odds_hwin_SJ,odds_awin_VC,odds_draw_VC,odds_hwin_VC,odds_awin_WH,odds_draw_WH,odds_hwin_WH
count,3420.000000,3420.000000,3420.000000,3420.000000,3420.000000,3420.000000,3420.000000,3420.000000,3420.000000,1520.000000,1520.000000,1520.000000,3419.000000,3419.000000,3419.000000,3420.000000,3410.000000,3410.000000,3420.000000,3420.000000,3420.000000,3410.000000,3410.000000,3420.000000,3420.000000,3420.000000,3420.000000,3420.000000,3410.000000,3410.000000,3420.000000,3420.000000,3420.000000,3420.000000,3420.000000,1519.000000,1519.00000,1519.000000,3420.000000,3420.000000,3420.000000,3420.00000,3420.000000,3420.000000,3420.000000,3420.000000,3419.000000,3419.000000,3419.000000,3419.000000,3419.000000,3419.000000,2280.00000,2280.000000,2280.000000,2280.000000,2280.000000,2280.000000,1140.000000,1140.000000,1140.000000,1940.000000,1940.00000,1940.000000,3420.000000,3420.000000,3420.000000,3420.000000,3420.000000,3420.000000
mean,4.798830,11.225439,0.088304,11.238596,4.856725,1.780994,5.009833,4.058368,2.782535,4.816303,3.803553,2.613954,4.631881,3.916280,2.686332,41.432456,23.386217,-0.310704,1.973713,1.878915,4.802705,2.091437,1.943721,3.936816,2.721158,2.078985,1.967638,5.454067,2.195827,2.016774,4.233015,2.913275,37.059357,1.171930,1.570760,4.597367,3.79973,2.601745,6.064035,10.670468,0.060819,14.18655,6.151462,0.516667,0.692982,1.473099,4.360895,3.795920,2.591536,4.724861,3.905624,2.694027,5.07011,5.077013,4.207500,2.860956,4.178061,2.840009,4.598114,3.773650,2.577483,4.893897,3.92382,2.666593,5.091821,4.065421,2.801356,4.813465,3.755058,2.738898
std,2.737924,3.578035,0.296875,4.691267,2.937379,1.292425,4.151425,1.152180,1.853622,3.853876,0.868362,1.630953,3.525104,1.033997,1.685014,5.741466,4.432551,0.801063,0.311321,0.249834,3.813080,0.958042,0.488168,1.040955,1.740754,0.354544,0.273634,4.861850,1.228692,0.594828,1.286891,2.007678,5.687097,1.158524,1.323608,3.349595,0.87315,1.578228,3.147304,3.405242,0.247450,5.47597,3.491834,0.731614,0.836368,1.195992,3.185530,0.873351,1.506886,3.764197,1.002289,1.705238,4.18971,4.214597,1.340505,1.910688,1.243858,1.873857,3.517203,0.878153,1.631384,3.890396,0.95571,1.686373,4.272137,1.149971,1.879163,3.891314,0.950410,1.739376
min,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.180000,3.000000,1.080000,1.220000,3.000000,1.100000,1.180000,2.900000,1.070000,26.000000,7.000000,-2.750000,1.400000,1.230000,1.180000,1.050000,1.010000,2.930000,1.090000,1.450000,1.250000,1.210000,1.070000,1.010000,3.100000,1.110000,8.000000,0.000000,0.000000,1.250000,3.00000,1.100000,0.000000,2.000000,0.000000,1.00000,0.000000,0.000000,0.000000,0.000000,1.200000,3.000000,1.050000,1.180000,2.900000,1.080000,1.20000,1.160000,2.890000,1.080000,2.950000,1.090000,1.200000,3.100000,1.080000,1.250000,3.00000,1.110000,1.180000,2.500000,1.060000,1.200000,2.800000,1.100000
25%,3.000000,9.000000,0.000000,8.000000,3.000000,1.000000,2.400000,3.400000,1.670000,2.500000,3.250000,1.620000,2.400000,3.300000,1.650000,37.000000,20.000000,-0.750000,1.750000,1.700000,2.420000,1.840000,1.810000,3.300000,1.650000,1.830000,1.770000,2.525000,1.890000,1.860000,3.450000,1.700000,33.000000,0.000000,1.000000,2.400000,3.25000,1.600000,4.000000,8.000000,0.000000,10.00000,4.000000,0.000000,0.000000,1.000000,2.400000,3.300000,1.650000,2.400000,3.300000,1.660000,2.44750,2.420000,3.410000,1.680000,3.430000,1.687500,2.400000,3.250000,1.570000,2.400000,3.30000,1.620000,2.450000,3.400000,1.670000,2.400000,3.200000,1.670000
50%,4.000000,11.000000,0.000000,11.000000,4.000000,2.000000,3.500000,3.600000,2.200000,3.400000,3.400000,2.100000,3.400000,3.500000,2.150000,40.000000,23.000000,-0.250000,1.910000,1.880000,3.470000,1.950000,1.910000,3.500000,2.160000,2.000000,1.960000,3.750000,2.010000,1.970000,3.700000,2.250000,37.000000,1.000000,1.000000,3.400000,3.40000,2.100000,6.000000,11.000000,0.000000,14.00000,6.000000,0.000000,0.000000,1.000000,3.300000,3.450000,2.100000,3.400000,3.500000,2.150000,3.63000,3.600000,3.680000,2.240000,3.695000,2.220000,3.275000,3.400000,2.100000,3.500000,3.50000,2.100000,3.600000,3.600000,2.200000,3.400000,3.400000,2.200000
75%,6.000000,14.000000,0.000000,14.000000,6.000000,3.000000,5.750000,4.200000,3.000000,5.500000,4.000000,2.800000,5.300000,4.100000,2.950000,46.000000,27.000000,0.000000,2.120000,2.050000,5.505000,2.060000,2.030000,4.130000,2.980000,2.250000,2.150000,6.030000,2.130000,2.090000,4.450000,3.200000,41.000000,2.000000,2.000000,5.500000,4.00000,2.850000,8.000000,13.000000,0.000000,17.00000,8.000000,1.000000,1.000000,2.000000,5.000000,3.900000,2.750000,5.500000,4.000000,3.000000,5.62000,5.732500,4.440000,3.200000,4.390000,3.160000,5.500000,3.800000,2.750000,5.800000,4.00000,2.880000,5.750000,4.300000,3.100000,5.500000,4.000000,3.000000
max,19.000000,26.000000,2.000000,30.000000,20.000000,9.000000,34.000000,13.000000,17.000000,26.000000,8.500000,13.000000,29.000000,12.000000,15.000000,57.000000,37.000000,2.000000,4.070000,2.910000,28.000000,15.140000,9.300000,11.570000,15.710000,4.420000,3.140000,34.000000,21.580000,13.000000,14.000000,19.000000,50.000000,7.000000,9.000000,21.000000,8.50000,12.000000,19.000000,24.000000,2.000000,43.00000,24.000000,5.000000,5.000000,7.000000,25.000000,10.000000,15.000000,29.000000,12.000000,17.000000,28.50000,30.000000,15.000000,18.000000,13.620000,15.500000,21.000000,8.500000,12.000000,29.000000,9.00000,15.000000,31.000000,13.000000,18.000000,26.000000,11.000000,17.000000

In [6]:
seasons_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3420 entries, 0 to 379
Data columns (total 74 columns):
a_corners                  3420 non-null int64
a_fouls                    3420 non-null int64
a_rcards                   3420 non-null int64
a_shots                    3420 non-null int64
a_sot                      3420 non-null int64
a_ycards                   3420 non-null int64
a                          3420 non-null object
odds_awin_bet365           3420 non-null float64
odds_draw_bet365           3420 non-null float64
odds_hwin_bet365           3420 non-null float64
odds_awin_BS               1520 non-null float64
odds_draw_BS               1520 non-null float64
odds_hwin_BS               1520 non-null float64
odds_awin_BW               3419 non-null float64
odds_draw_BW               3419 non-null float64
odds_hwin_BW               3419 non-null float64
n_Bb1X2                    3420 non-null int64
n_BbAsian                  3410 non-null float64
BbAsian_handicap           3410 non-null float64
odds_ftgoalsu2.5_bbmean    3420 non-null float64
odds_ftgoalso2.5_bbmean    3420 non-null float64
odds_awin_bbmean           3420 non-null float64
odds_asianaway_bbmean      3410 non-null float64
odds_asianaway_bbmean      3410 non-null float64
odds_draw_bbmean           3420 non-null float64
odds_hwin_bbmean           3420 non-null float64
odds_ftgoalsu2.5_bbmax     3420 non-null float64
odds_ftgoalso2.5_bbmax     3420 non-null float64
odds_awin_bbmax            3420 non-null float64
odds_asianaway_bbmax       3410 non-null float64
odds_asianhome_bbmax       3410 non-null float64
odds_draw_bbmax            3420 non-null float64
odds_hwin_bbmax            3420 non-null float64
n_BbOU                     3420 non-null int64
date                       3420 non-null datetime64[ns]
a_ftgoals                  3420 non-null int64
h_ftgoals                  3420 non-null int64
odds_awin_GB               1519 non-null float64
odds_draw_GB               1519 non-null float64
odds_hwin_GB               1519 non-null float64
h_corners                  3420 non-null int64
h_fouls                    3420 non-null int64
h_rcards                   3420 non-null int64
h_shots                    3420 non-null int64
h_sot                      3420 non-null int64
a_htgoals                  3420 non-null int64
h_htgoals                  3420 non-null int64
h_ycards                   3420 non-null int64
h                          3420 non-null object
odds_awin_IW               3419 non-null float64
odds_draw_IW               3419 non-null float64
odds_hwin_IW               3419 non-null float64
odds_awin_LB               3419 non-null float64
odds_draw_LB               3419 non-null float64
odds_hwin_LB               3419 non-null float64
odds_awin_pinn             2280 non-null float64
clodds_away_pinn           2280 non-null float64
clodds_draw_pinn           2280 non-null float64
clodds_hwin_pinn           2280 non-null float64
odds_draw_pinn             2280 non-null float64
odds_hwin_pinn             2280 non-null float64
odds_awin_SB               1140 non-null float64
odds_draw_SB               1140 non-null float64
odds_hwin_SB               1140 non-null float64
odds_awin_SJ               1940 non-null float64
odds_draw_SJ               1940 non-null float64
odds_hwin_SJ               1940 non-null float64
odds_awin_VC               3420 non-null float64
odds_draw_VC               3420 non-null float64
odds_hwin_VC               3420 non-null float64
odds_awin_WH               3420 non-null float64
odds_draw_WH               3420 non-null float64
odds_hwin_WH               3420 non-null float64
season                     3420 non-null object
dtypes: datetime64[ns](1), float64(52), int64(18), object(3)
memory usage: 2.0+ MB

In [7]:
seasons_df.to_csv(INTERIM_DATA_DIR / league / save_file_name, index=False)

## Read Back Data

In [8]:
df = pd.read_csv(INTERIM_DATA_DIR / league / save_file_name,
                      parse_dates=['date'], index_col=None)
df.head()

,a_corners,a_fouls,a_rcards,a_shots,a_sot,a_ycards,a,odds_awin_bet365,odds_draw_bet365,odds_hwin_bet365,odds_awin_BS,odds_draw_BS,odds_hwin_BS,odds_awin_BW,odds_draw_BW,odds_hwin_BW,n_Bb1X2,n_BbAsian,BbAsian_handicap,odds_ftgoalsu2.5_bbmean,odds_ftgoalso2.5_bbmean,odds_awin_bbmean,odds_asianaway_bbmean,odds_asianaway_bbmean.1,odds_draw_bbmean,odds_hwin_bbmean,odds_ftgoalsu2.5_bbmax,odds_ftgoalso2.5_bbmax,odds_awin_bbmax,odds_asianaway_bbmax,odds_asianhome_bbmax,odds_draw_bbmax,odds_hwin_bbmax,n_BbOU,date,a_ftgoals,h_ftgoals,odds_awin_GB,odds_draw_GB,odds_hwin_GB,h_corners,h_fouls,h_rcards,h_shots,h_sot,a_htgoals,h_htgoals,h_ycards,h,odds_awin_IW,odds_draw_IW,odds_hwin_IW,odds_awin_LB,odds_draw_LB,odds_hwin_LB,odds_awin_pinn,clodds_away_pinn,clodds_draw_pinn,clodds_hwin_pinn,odds_draw_pinn,odds_hwin_pinn,odds_awin_SB,odds_draw_SB,odds_hwin_SB,odds_awin_SJ,odds_draw_SJ,odds_hwin_SJ,odds_awin_VC,odds_draw_VC,odds_hwin_VC,odds_awin_WH,odds_draw_WH,odds_hwin_WH,season
0,6,14,0,14,7,2,Wigan,5.50,3.60,1.67,5.5,3.5,1.62,5.00,3.40,1.65,37,21.0,0.0,1.81,1.92,5.33,3.99,1.22,3.51,1.66,1.91,2.04,6.05,4.40,1.28,3.77,1.72,32,2009-08-15,2,0,5.25,3.50,1.67,4,15,0,11,5,1,0,2,Aston Villa,4.9,3.5,1.7,4.50,3.3,1.67,NaN,NaN,NaN,NaN,NaN,NaN,5.0,3.40,1.65,5.50,3.60,1.67,5.0,3.4,1.70,5.50,3.4,1.70,2009-2010
1,4,9,0,8,5,1,Man City,2.10,3.25,3.60,2.2,3.2,3.30,2.00,3.15,3.40,38,24.0,0.0,1.71,2.04,2.12,1.54,2.38,3.24,3.37,1.78,2.15,2.25,1.60,2.58,3.35,3.78,33,2009-08-15,2,0,2.10,3.25,3.40,5,12,0,17,9,1,0,2,Blackburn,2.2,3.2,3.2,2.10,3.2,3.00,NaN,NaN,NaN,NaN,NaN,NaN,2.1,3.25,3.15,2.20,3.25,3.30,2.2,3.2,3.25,2.15,3.2,3.50,2009-2010
2,7,10,0,20,13,1,Sunderland,3.25,3.25,2.25,3.3,3.2,2.20,3.15,3.15,2.15,38,23.0,0.0,1.66,2.12,3.15,2.23,1.61,3.20,2.24,1.70,2.25,3.40,2.33,1.68,3.31,2.37,33,2009-08-15,1,0,3.10,3.25,2.25,4,16,0,11,3,1,0,2,Bolton,3.2,3.2,2.2,3.00,3.2,2.10,NaN,NaN,NaN,NaN,NaN,NaN,2.9,3.20,2.25,3.10,3.25,2.30,3.1,3.2,2.25,3.20,3.2,2.30,2009-2010
3,4,15,0,7,3,2,Hull,21.00,6.50,1.17,19.0,5.5,1.20,13.00,6.00,1.17,38,22.0,0.0,2.26,1.58,16.39,12.96,1.02,6.26,1.17,2.44,1.67,23.14,17.05,1.03,7.71,1.20,34,2009-08-15,1,2,15.00,6.00,1.20,12,13,0,26,12,1,1,1,Chelsea,14.0,5.5,1.2,12.00,5.5,1.17,NaN,NaN,NaN,NaN,NaN,NaN,15.0,5.75,1.17,17.00,6.50,1.18,17.0,6.0,1.17,21.00,6.5,1.17,2009-2010
4,9,13,0,15,9,0,Arsenal,2.30,3.25,3.20,2.2,3.2,3.25,2.25,3.15,2.95,38,24.0,0.0,1.70,2.06,2.28,1.63,2.20,3.21,3.07,1.77,2.20,2.42,1.73,2.27,3.34,3.34,34,2009-08-15,6,1,2.30,3.25,3.00,4,11,0,8,5,3,0,0,Everton,2.3,3.1,3.1,2.25,3.0,2.88,NaN,NaN,NaN,NaN,NaN,NaN,2.2,3.20,3.00,2.25,3.25,3.25,2.3,3.3,2.90,2.30,3.2,3.20,2009-2010

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3420 entries, 0 to 3419
Data columns (total 74 columns):
a_corners                  3420 non-null int64
a_fouls                    3420 non-null int64
a_rcards                   3420 non-null int64
a_shots                    3420 non-null int64
a_sot                      3420 non-null int64
a_ycards                   3420 non-null int64
a                          3420 non-null object
odds_awin_bet365           3420 non-null float64
odds_draw_bet365           3420 non-null float64
odds_hwin_bet365           3420 non-null float64
odds_awin_BS               1520 non-null float64
odds_draw_BS               1520 non-null float64
odds_hwin_BS               1520 non-null float64
odds_awin_BW               3419 non-null float64
odds_draw_BW               3419 non-null float64
odds_hwin_BW               3419 non-null float64
n_Bb1X2                    3420 non-null int64
n_BbAsian                  3410 non-null float64
BbAsian_handicap           3410 non-null float64
odds_ftgoalsu2.5_bbmean    3420 non-null float64
odds_ftgoalso2.5_bbmean    3420 non-null float64
odds_awin_bbmean           3420 non-null float64
odds_asianaway_bbmean      3410 non-null float64
odds_asianaway_bbmean.1    3410 non-null float64
odds_draw_bbmean           3420 non-null float64
odds_hwin_bbmean           3420 non-null float64
odds_ftgoalsu2.5_bbmax     3420 non-null float64
odds_ftgoalso2.5_bbmax     3420 non-null float64
odds_awin_bbmax            3420 non-null float64
odds_asianaway_bbmax       3410 non-null float64
odds_asianhome_bbmax       3410 non-null float64
odds_draw_bbmax            3420 non-null float64
odds_hwin_bbmax            3420 non-null float64
n_BbOU                     3420 non-null int64
date                       3420 non-null datetime64[ns]
a_ftgoals                  3420 non-null int64
h_ftgoals                  3420 non-null int64
odds_awin_GB               1519 non-null float64
odds_draw_GB               1519 non-null float64
odds_hwin_GB               1519 non-null float64
h_corners                  3420 non-null int64
h_fouls                    3420 non-null int64
h_rcards                   3420 non-null int64
h_shots                    3420 non-null int64
h_sot                      3420 non-null int64
a_htgoals                  3420 non-null int64
h_htgoals                  3420 non-null int64
h_ycards                   3420 non-null int64
h                          3420 non-null object
odds_awin_IW               3419 non-null float64
odds_draw_IW               3419 non-null float64
odds_hwin_IW               3419 non-null float64
odds_awin_LB               3419 non-null float64
odds_draw_LB               3419 non-null float64
odds_hwin_LB               3419 non-null float64
odds_awin_pinn             2280 non-null float64
clodds_away_pinn           2280 non-null float64
clodds_draw_pinn           2280 non-null float64
clodds_hwin_pinn           2280 non-null float64
odds_draw_pinn             2280 non-null float64
odds_hwin_pinn             2280 non-null float64
odds_awin_SB               1140 non-null float64
odds_draw_SB               1140 non-null float64
odds_hwin_SB               1140 non-null float64
odds_awin_SJ               1940 non-null float64
odds_draw_SJ               1940 non-null float64
odds_hwin_SJ               1940 non-null float64
odds_awin_VC               3420 non-null float64
odds_draw_VC               3420 non-null float64
odds_hwin_VC               3420 non-null float64
odds_awin_WH               3420 non-null float64
odds_draw_WH               3420 non-null float64
odds_hwin_WH               3420 non-null float64
season                     3420 non-null object
dtypes: datetime64[ns](1), float64(52), int64(18), object(3)
memory usage: 1.9+ MB